import { CampaignCategory } from "@/utils/campaignCategory"
import { IPagination } from "."

export interface ICampaign {
  _id: string
  userId: string
  category: CampaignCategory
  title: string
  story: string
  campaignType: CampaignType
  campaignStatus: CampaignStatus
  campaignCoverImage: CampaignCoverImage
  campaignAdditionalImages: any[]
  campaignViews: number
  fundraise: Fundraise
  allDonors: number
  allVolunteers: number
  __v: number
}

export interface CampaignCoverImage {
  _id: string
  url: string
  public_id: string
  id: string
}

export interface Fundraise {
  fundingGoalDetails: FundingGoalDetail[]
  startOfFundraise: string
  endOfFundraise: string
}

export interface FundingGoalDetail {
  amount: number
  currency: string
}

export interface CampaignResponse {
  campaigns: ICampaign[]
  pagination: IPagination
}

export type CampaignStatus =
  | "completed"
  | "in-progress"
  | "declined"
  | "in-review"
export type CampaignType = "fundraise" | "volunteer" | "fundraiseAndVolunteer"

// Generated by https://quicktype.io

export interface CampaignStatsResponse {
  success: boolean
  message: string
  data: ICampaignStats
}

export interface ICampaignStats {
  totalAmountDonated: TotalAmountDonated[]
  totalNoOfCampaigns: number
  totalCampaignViews: number
}

export interface DonationStatsResponse {
  success: boolean
  message: string
  data: IDonationStats
}

export interface IDonationStats {
  totalAmountDonated: TotalAmountDonated[]
  totalNoOfCampaigns: number
}

export interface TotalAmountDonated {
  currency: string
  totalAmount: number
}

// Generated by https://quicktype.io

export interface IDonationResponse {
  donations: IDonation[]
  pagination: IPagination
}

export interface IDonation {
  _id: string
  campaignOwnerId: string
  campaignDonorId: string
  campaignId: string
  amount: string
  email: string
  currency: string
  fullName: string
  isAnonymous: boolean
  shouldShareDetails: boolean
  isSubscribedToPromo: boolean
  transactionRef: string
  createdAt: string
  updatedAt: string
}

export interface IVolunteeringResponse {
  volunteers: IVolunteer[]
  pagination: IPagination
}

export interface IVolunteer {
  _id: string
  campaignId: string
  userId: string
  fullName: string
  email: string
  gender: string
  ageRange: string
  address: string
  about: string
  phoneNumber: string
  createdAt: string
  updatedAt: string
}
